from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
TRACE_PATH = ROOT / "outputs" / "trace.json"
COLLAB_PATH = ROOT / "outputs" / "collab_summary.csv"
OUT_PATH = ROOT / "docs" / "DEMO_REPORT.md"


def _load_trace() -> Dict[str, Any]:
    return json.loads(TRACE_PATH.read_text())


def _load_collab_excerpt(max_lines: int = 6) -> str:
    if not COLLAB_PATH.exists():
        return ""
    rows = []
    with COLLAB_PATH.open(newline="") as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            rows.append(", ".join(row))
            if i >= max_lines:
                break
    return "\n".join(rows)


def _group_events_by_turn(events: List[Dict[str, Any]]) -> Dict[int, List[Dict[str, Any]]]:
    grouped: Dict[int, List[Dict[str, Any]]] = {}
    current_turn = None
    for event in events:
        if event.get("event") == "turn_start":
            current_turn = event.get("turn_id")
            grouped.setdefault(current_turn, []).append(event)
            continue
        if current_turn is None:
            continue
        grouped[current_turn].append(event)
    return grouped


def _snapshot_by_turn(snapshots: List[Dict[str, Any]]) -> Dict[int, Dict[str, Any]]:
    return {snap.get("turn_id"): snap for snap in snapshots}


def _render_turn(turn_id: int, events: List[Dict[str, Any]], snapshot: Dict[str, Any] | None) -> str:
    text = None
    response = None
    diff = {}
    duration = None
    decision = None
    intent = None

    if snapshot:
        intent = snapshot.get("intent")
        decision = snapshot.get("meta", {}).get("decision")

    for event in events:
        if event.get("event") == "turn_start":
            text = event.get("text")
        elif event.get("event") == "task_response":
            response = event.get("response")
        elif event.get("event") == "state_diff" and event.get("agent") == "langgraph":
            diff = event.get("diff", {})
        elif event.get("event") == "node_duration" and event.get("agent") == "langgraph":
            duration = event.get("ms")

    lines = []
    lines.append(f"### Turn {turn_id}")
    if text:
        lines.append(f"- User text: {text}")
    if intent:
        lines.append(f"- Intent: {intent}")
    if decision:
        lines.append(f"- Supervisor decision: {decision}")
    if duration is not None:
        lines.append(f"- Orchestrator duration: {duration} ms")
    if diff:
        diff_keys = ", ".join(diff.keys())
        lines.append(f"- Fields written: {diff_keys}")
    if response:
        lines.append(f"- Response: {response}")
    return "\n".join(lines)


def main() -> None:
    trace = _load_trace()
    events = trace.get("events", [])
    snapshots = trace.get("snapshots", [])
    grouped = _group_events_by_turn(events)
    snap_by_turn = _snapshot_by_turn(snapshots)

    collab_excerpt = _load_collab_excerpt()

    sections = []
    sections.append("# End-to-End Demo Report (Auto-Generated)\n")
    sections.append("Date: 2026-03-11\n")
    sections.append(
        "This file is generated by `scripts/generate_demo_report.py`. "
        "Do not edit manually."
    )

    sections.append("\n## Summary")
    sections.append(
        "This report captures the latest end-to-end run using text-mode input (no voice) "
        "and renders the agent collaboration trace in three visualizations: table, swimlane, and timeline."
    )

    sections.append("\n## Artifacts Generated")
    sections.append("- `outputs/trace.json`")
    sections.append("- `outputs/trace.html`")
    sections.append("- `outputs/trace_swimlane.html`")
    sections.append("- `outputs/trace_timeline.html`")
    sections.append("- `outputs/collab_summary.csv`")
    sections.append("- Screenshots:")
    sections.append("  - `output/playwright/trace_table.png`")
    sections.append("  - `output/playwright/trace_swimlane.png`")
    sections.append("  - `output/playwright/trace_timeline.png`")

    sections.append("\n## Visuals")
    sections.append("### Trace Table")
    sections.append("![Trace Table](/Users/jinniu/Documents/GitHub/ClinicVoxAI/output/playwright/trace_table.png)")
    sections.append("\n### Swimlane")
    sections.append("![Swimlane](/Users/jinniu/Documents/GitHub/ClinicVoxAI/output/playwright/trace_swimlane.png)")
    sections.append("\n### Timeline")
    sections.append("![Timeline](/Users/jinniu/Documents/GitHub/ClinicVoxAI/output/playwright/trace_timeline.png)")

    sections.append("\n## Collaboration Summary (Excerpt)")
    sections.append("Source: `outputs/collab_summary.csv`\n")
    if collab_excerpt:
        sections.append("```")
        sections.append(collab_excerpt)
        sections.append("```")
    else:
        sections.append("(collab summary not found)")

    sections.append("\n## Turn-by-Turn Walkthrough (Auto)\n")
    for turn_id in sorted(grouped.keys()):
        sections.append(_render_turn(turn_id, grouped[turn_id], snap_by_turn.get(turn_id)))
        sections.append("")

    sections.append("## Interpretation Notes")
    sections.append("- Each turn logs `state_diff` so you can see which fields changed per agent.")
    sections.append("- Context version increments indicate intent switches and resets.")
    sections.append("- `node_duration` records per-turn LangGraph execution time in ms.")

    sections.append("\n## How This Was Produced")
    sections.append("1. `pytest -q`")
    sections.append("2. `PYTHONPATH=. python scripts/run_all_demos.py`")
    sections.append("3. `PYTHONPATH=. python scripts/export_events.py`")
    sections.append("4. `PYTHONPATH=. python scripts/render_trace_html.py`")
    sections.append("5. `PYTHONPATH=. python scripts/render_trace_swimlane.py`")
    sections.append("6. `PYTHONPATH=. python scripts/render_trace_timeline.py`")
    sections.append("7. `PYTHONPATH=. python scripts/render_collab_summary.py`")
    sections.append("8. Screenshots via Playwright CLI")

    OUT_PATH.write_text("\n".join(sections))
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
